- name: required packages are installed
  become: true
  package:
    name:
      - make
      - git

- name: pull tic docker
  become: true
  become_user: tic
  git:
    repo: https://github.com/0b11stan/docker-tic.git
    dest: /home/tic/docker-tic/
    track_submodules: true
    force: yes

- name: deploy apps
  become: true
  docker_compose:
    project_name: tic
    project_src: /home/tic/docker-tic/
    build: true
    nocache: true
