- name: create required docker volumes
  become: true
  command: "docker volume create {{ item }}"
  args:
    creates: "{{ docker_volumes_path }}/{{ item }}"
  loop:
    - nextcloud
    - database

- name: required packages are installed
  become: true
  package:
    state: present
    name:
      - git
      - python-pip

- name: required pip packages are installed
  become: true
  pip:
    name:
      - docker<4.0
      - docker-compose

- name: pull tic docker
  become: true
  git:
    repo: https://github.com/0b11stan/docker-tic.git
    dest: /srv/docker-tic/

- name: deploy apps
  become: true
  docker_compose:
    build: true
    project_name: tic
    project_src: /srv/docker-tic/
  environment:
    DATABASE_ROOT_PASSWORD: "{{ db_root_password }}"
    DATABASE_PASSWORD: "{{ db_password }}"
