version: '3.7'

volumes:
  nextcloud:
  db:

services:
  nextcloud:
    ports:
      - 8080:80
    image: nextcloud
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=azerty
      - MYSQL_PASSWORD=qwerty
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
