version: '3.7'

volumes:
  nextcloud:
  db:


services:

  proxy:
    restart: always
    build: ./reverse-proxy
    ports:
      - 80:80
    links:
      - nextcloud
      - flexfactory

  nextcloud:
    image: nextcloud
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always

  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  flexfactory:
    image: flexfactory:latest
    build: ./flexfactory
